# Generated by Django 4.2.3 on 2023-08-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_VS_Subject',
            new_name='Teacher_VS_Subjects',
        ),
    ]
