# Generated by Django 4.2.4 on 2023-09-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago', models.BigIntegerField()),
                ('id_padre', models.IntegerField()),
                ('id_estudiante', models.IntegerField()),
                ('fecha_pago', models.DateTimeField()),
                ('monto_total', models.FloatField()),
                ('estado', models.SmallIntegerField()),
            ],
        ),
    ]
