# Generated by Django 4.2.4 on 2023-09-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField()),
                ('inicio_escolar', models.DateTimeField()),
                ('fin_escolar', models.DateTimeField()),
            ],
        ),
    ]
