# Generated by Django 4.2.4 on 2023-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField()),
                ('nombre_user', models.BigIntegerField()),
                ('password', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('estado', models.SmallIntegerField()),
            ],
        ),
    ]
