# Generated by Django 4.2.3 on 2023-09-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.calification'),
        ),
        migrations.DeleteModel(
            name='calification',
        ),
    ]
