# Generated by Django 4.2.4 on 2023-09-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_calification_inscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calification',
            name='inscription_id',
        ),
    ]
