# Generated by Django 4.2.4 on 2023-09-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
        ('teachers', '0005_remove_calification_inscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_calification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPeriod', models.IntegerField(null=True)),
                ('secondPeriod', models.IntegerField(null=True)),
                ('thirdPeriod', models.IntegerField(null=True)),
                ('fourthPeriod', models.IntegerField(null=True)),
                ('finish', models.IntegerField(null=True)),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.subject')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.students')),
            ],
        ),
    ]
